### ISSUE TITLE
Environment table improvements

### ISSUE THREAD

**Issue by aammd** [ReseauBiodiversiteQuebec/tableauexplosites#2]
For the environment table (currently in the modal)

- [x] add explanatory text to make the figure legible
- [x] change title for modal -- cell name and habitat type
- [ ] mouseover a line to get the name of THAT site

**Comment by aammd** [comment]
<img width="281" alt="image" src="https://user-images.githubusercontent.com/1198242/120700574-d0ecc280-c47f-11eb-8c2b-f257b554b3a0.png">

The most I accomplished for the last point was making the plots rendered separately and removing the dependency on patchwork. Turns out there is no easy way to make ggplotly play nicely with coord_polar [this issue](https://github.com/ropensci/plotly/issues/878)

**Comment by aammd** [comment]
perhaps ggirafe?

**Comment by aammd** [comment]
ggirafe is promising, but I can't get the tooltip to work within the modal only. If I create the plot outside the modal, it works fine. Might be related to this https://github.com/davidgohel/ggiraph/issues/150 but I tried the fix described there (commit linked above) and it didn't seem to do anything.  @glaroc any ideas about what might be the trouble? its a CSS thing, it seems.

**Comment by glaroc** [comment]
The tooltip seems to work for me within the modal.
